import React from 'react';

// --- DESIGN SYSTEM: SOULCODE LMS ---
export const THEME = {
    bg: 'var(--color-bg)',
    side: 'var(--color-side)',
    sideHover: 'var(--color-side-hover)',
    accent: 'var(--color-bg-gradient-main)',
    accent2: 'var(--color-accent-r)',
    accentR: 'var(--color-accent-r)',
    accentPurple: '#a855f7',
    glass: 'var(--color-glass)',
    glassBright: 'var(--color-glass-bright)',
    border: 'var(--color-border)',
    borderHover: 'var(--color-border-hover)',
    text: 'var(--color-text)',
    textS: 'var(--color-text-s)',
    textM: 'var(--color-text-m)',
    success: 'var(--color-success)',
    successBg: 'var(--color-success-bg)',
    danger: '#ef4444',
    dangerBg: 'rgba(239,68,68,0.1)',
    info: 'var(--color-info)',
    infoBg: 'var(--color-info-bg)',
    warning: 'var(--color-warning)',
    shadow: 'var(--color-shadow)',
    shadowSm: '0 1px 2px 0 var(--color-shadow)',
    shadowMd: '0 4px 6px -1px var(--color-shadow), 0 2px 4px -1px var(--color-shadow)',
    shadowLg: '0 10px 15px -3px var(--color-shadow), 0 4px 6px -2px var(--color-shadow)',
};

export const STYLES: Record<string, React.CSSProperties> = {
    app: {
        minHeight: '100vh',
        background: 'var(--color-bg-gradient)',
        color: THEME.text,
        fontFamily: `'Arima', cursive, 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif`,
        backgroundAttachment: 'fixed',
    },
    sidebar: {
        width: '260px',
        background: 'var(--color-sidebar-bg)',
        borderRight: `1px solid ${THEME.border}`,
        padding: '28px 16px',
        position: 'fixed',
        height: '100vh',
        left: 0, top: 0, zIndex: 100,
        display: 'flex',
        flexDirection: 'column',
    },
    view: { marginLeft: '260px', padding: '32px 48px', minHeight: '100vh' },
    card: {
        background: 'var(--color-glass-bright)',
        backdropFilter: 'blur(10px)',
        border: '1px solid var(--color-border)',
        borderRadius: '24px',
        padding: '32px',
        boxShadow: '0 10px 40px var(--color-shadow)',
        transition: 'all 0.3s ease',
    },
    input: {
        background: 'var(--color-bg)',
        border: `1px solid ${THEME.border}`,
        padding: '0 16px',
        height: '48px',
        borderRadius: '8px',
        color: THEME.text,
        fontSize: '14px',
        width: '100%',
        marginBottom: '14px',
        outline: 'none',
        transition: 'border-color 0.2s, box-shadow 0.2s',
        boxSizing: 'border-box',
    },
    btn: {
        background: THEME.accent,
        border: 'none',
        borderRadius: '4px',
        padding: '11px 24px',
        color: 'var(--color-text)',
        fontWeight: '700',
        cursor: 'pointer',
        fontSize: '13px',
        transition: 'opacity 0.2s, box-shadow 0.2s',
        boxShadow: 'none',
        letterSpacing: '0.3px',
    },
    modalForm: {},
    table: { width: '100%', borderCollapse: 'collapse', borderSpacing: '0', textAlign: 'left' },
    th: {
        padding: '14px 18px',
        color: 'var(--color-text)',
        fontSize: '12px',
        fontWeight: '700',
        background: 'var(--color-table-header)',
        borderBottom: `1px solid ${THEME.border}`,
    },
    td: {
        padding: '15px 18px',
        fontSize: '14px',
        borderBottom: `1px solid ${THEME.border}`,
    },
    securityOverlay: { position: 'fixed', inset: 0, pointerEvents: 'none', zIndex: 9999 },
};

export const CSS_ANIMATIONS = ``; // Moved to index.css

